name: py

on: 
  push:
    branches: ["main"]

  workflow_dispatch:


jobs:
  scirpt:
    runs-on: ubuntu-latest
    steps: 
      - uses: action/checkout@v3

      - name: Rua a one-line script
        run: echo this is python script runner